"""η (reinstatement-efficiency) sensitivity sweep — CURRENT engine.

Supersedes `output/sigma_sensitivity.parquet`, which was generated by
`sigma_sensitivity.py` sweeping the legacy `sigma` alias. Under the current
engine the CES vacancy kernel reads `reinstatement_efficiency` directly when
`sigma_elast >= 0.5` (see agents/Employer.py:_generate_vacancies), so the old
sweep no longer moved η. This script sets `reinstatement_efficiency` explicitly.

Sweeps η ∈ {0.005, 0.01, 0.02, 0.04, 0.08} (sixteen-fold range) × N_RUNS paired
seeds, current engine, same 180-tick / 60-burn-in analysis window as
paired_runs.parquet. Output: output/eta_sensitivity_v2.parquet — schema matches
paired_runs.parquet plus a leading `eta` column.

CLI
---
    python scripts/eta_sensitivity.py                 # full: grid × 100 seeds, 180 ticks
    python scripts/eta_sensitivity.py --smoke         # 2 seeds, 2 η, 30 ticks (schema check)
    python scripts/eta_sensitivity.py --n-runs 100 --grid 0.005,0.01,0.02,0.04,0.08
"""
from __future__ import annotations

import argparse
import multiprocessing as mp
import pathlib
import sys
import time
from datetime import datetime, timedelta

ROOT = pathlib.Path(__file__).parent.parent.resolve()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd

from model.LaborMarketModel import LaborMarketModel, DEFAULT_PARAMS

DEFAULT_GRID = (0.005, 0.01, 0.02, 0.04, 0.08)
N_RUNS       = 100
N_TICKS      = 180
BURN_IN      = 60
OUT_PATH     = ROOT / "output" / "eta_sensitivity_v2.parquet"
N_WORKERS    = min(mp.cpu_count(), 8)
REPORT_EVERY = 10

# ── Worker-process state (populated by _worker_init in each pool process) ───────
_worker_df   = None
_dist_matrix = None
_occ_risk    = None
_n_ticks     = N_TICKS
_burn_in     = BURN_IN


def _worker_init(n_ticks: int, burn_in: int):
    global _worker_df, _dist_matrix, _occ_risk, _n_ticks, _burn_in
    from scripts.bootstrap_runner import load_shared_data  # noqa: PLC0415
    _worker_df, _dist_matrix, _occ_risk = load_shared_data()
    _n_ticks = n_ticks
    _burn_in = burn_in


def run_seed(task: tuple[int, float]) -> pd.DataFrame:
    """Run one paired (AI + Control) simulation at the given (seed, η)."""
    seed, eta = task
    rng = np.random.default_rng(seed)
    sampled_df = _worker_df.sample(
        n=len(_worker_df), replace=True,
        random_state=int(rng.integers(0, 2**31)),
    ).reset_index(drop=True)

    params = dict(DEFAULT_PARAMS)
    params["reinstatement_efficiency"] = float(eta)

    rows = []
    for scenario, ai_active in (("AI", True), ("Control", False)):
        m = LaborMarketModel(
            sampled_df,
            params=params,
            ai_active=ai_active,
            seed=seed,
            skill_distance_matrix=_dist_matrix,
            occ_risk_lookup=_occ_risk,
            collect_agent_data=False,
        )
        for _ in range(_n_ticks):
            m.step()

        df = m.datacollector.get_model_vars_dataframe().copy()
        df.index.name = "tick"
        df["seed"]     = seed
        df["scenario"] = scenario
        df["eta"]      = float(eta)
        df = df.reset_index()
        df = df[df["tick"] >= _burn_in].copy()
        df["tick"] = df["tick"] - _burn_in
        rows.append(df)

    return pd.concat(rows, ignore_index=True)


def _parse_grid(arg: str | None) -> tuple[float, ...]:
    if not arg:
        return DEFAULT_GRID
    return tuple(float(x.strip()) for x in arg.split(",") if x.strip())


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    p.add_argument("--grid", default=None,
                   help=f"comma-separated η values (default: {','.join(map(str, DEFAULT_GRID))})")
    p.add_argument("--n-runs", type=int, default=N_RUNS)
    p.add_argument("--n-ticks", type=int, default=N_TICKS)
    p.add_argument("--burn-in", type=int, default=BURN_IN)
    p.add_argument("--out", default=str(OUT_PATH))
    p.add_argument("--smoke", action="store_true",
                   help="fast schema check: 2 seeds, η∈{0.005,0.08}, 30 ticks (burn-in 10)")
    args = p.parse_args()

    if args.smoke:
        grid = (0.005, 0.08)
        n_runs, n_ticks, burn_in = 2, 30, 10
        out_path = pathlib.Path(args.out).with_name("eta_sensitivity_v2_smoke.parquet")
    else:
        grid = _parse_grid(args.grid)
        n_runs, n_ticks, burn_in = args.n_runs, args.n_ticks, args.burn_in
        out_path = pathlib.Path(args.out)

    total = len(grid) * n_runs
    print(
        f"[eta_sensitivity] reinstatement-efficiency (η) sweep — current engine\n"
        f"  η grid                : {list(grid)}\n"
        f"  paired seeds per η     : {n_runs}\n"
        f"  ticks per run          : {n_ticks} (burn-in {burn_in}, {n_ticks - burn_in} analysis)\n"
        f"  workers                : {N_WORKERS} (cpu_count={mp.cpu_count()}, capped at 8)\n"
        f"  paired tasks           : {total}  ({total * 2} single simulations)\n"
        f"  output                 : {out_path}\n",
        flush=True,
    )

    tasks = [(seed, eta) for eta in grid for seed in range(n_runs)]
    start_time = time.monotonic()
    print(f"  started at : {datetime.now():%Y-%m-%d %H:%M:%S}\n", flush=True)

    all_frames = []
    with mp.Pool(processes=N_WORKERS, initializer=_worker_init,
                 initargs=(n_ticks, burn_in)) as pool:
        for i, result in enumerate(pool.imap_unordered(run_seed, tasks), start=1):
            all_frames.append(result)
            if i % REPORT_EVERY == 0 or i == total:
                elapsed   = time.monotonic() - start_time
                rate      = i / elapsed
                remaining = (total - i) / rate if rate > 0 else 0
                eta_wall  = datetime.now() + timedelta(seconds=remaining)
                print(
                    f"  [{datetime.now():%H:%M:%S}]  {i:>4}/{total} paired tasks"
                    f"  |  elapsed: {elapsed/60:.1f}m  |  ETA: {eta_wall:%H:%M:%S}",
                    flush=True,
                )

    out_df = pd.concat(all_frames, ignore_index=True)
    out_df["unemployment_rate"] = 1.0 - out_df["Employment_Rate"]
    # Lead with `eta` for readability (schema = paired_runs columns + eta).
    out_df = out_df[["eta"] + [c for c in out_df.columns if c != "eta"]]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_parquet(out_path, index=False)
    print(f"\n[eta_sensitivity] Saved {len(out_df)} rows to {out_path}", flush=True)
    print(f"  columns: {list(out_df.columns)}", flush=True)
    print(f"  η values present: {sorted(out_df['eta'].unique())}", flush=True)
    print(f"  ticks: {out_df['tick'].min()}–{out_df['tick'].max()}, "
          f"seeds: {out_df['seed'].nunique()}, scenarios: {sorted(out_df['scenario'].unique())}",
          flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
