#!/usr/bin/env python3
"""
Regenerate appendix/viz_code.qmd from current sources.

Watched inputs (anything matching triggers regeneration):
  - manuscript_02.qmd            (visualization code chunks tagged `#| label: fig-...`)
  - model/**/*.py                (LaborMarketModel + helpers)
  - the curated WATCHED_SCRIPTS list below (calibration / preprocessing)

The hook in .claude/settings.json invokes this with --hook on every
Edit/Write/MultiEdit/NotebookEdit; it reads the tool JSON from stdin and
short-circuits if the file isn't watched. Run with no args to refresh manually.

The output file is rewritten only when content actually changes (idempotent),
so re-running is cheap and safe.

To change what gets included, edit WATCHED_SCRIPTS or MODEL_DIR.
The PDF is NOT auto-rebuilt -- run `quarto render manuscript_02.qmd` when ready.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR") or Path(__file__).resolve().parents[1])
QMD_PATH = ROOT / "manuscript_02.qmd"
APPENDIX_PATH = ROOT / "appendix" / "viz_code.qmd"
MODEL_DIR = ROOT / "model"
AGENTS_DIR = ROOT / "agents"

# Curated calibration / preprocessing / configuration / sensitivity scripts.
# Edit this list to add/remove. Paths are relative to ROOT.
WATCHED_SCRIPTS = [
    "scripts/abc_calibration.py",
    "scripts/paired_bootstrap.py",
    "scripts/calibrate_omega_mu.py",
    "scripts/anchor_sensitivity.py",
    "scripts/build_hard_skill_scores.py",
    "scripts/process_lookup_tables.py",
    "scripts/bootstrap_runner.py",
    "scripts/control_simulation.py",
    "scripts/smoke_test.py",
    "scripts/industry_analysis.py",
    "scripts/rq4_hard_skill_figure.py",
    "scripts/sigma_sensitivity.py",
    "scripts/info_noise_sensitivity.py",
    "scripts/q1_decomposition.py",
]


def _rel(path: Path | str) -> str:
    p = Path(path).resolve()
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p)


def hook_should_run(file_path: str) -> bool:
    """Return True if an edit to `file_path` should trigger regeneration."""
    if not file_path:
        return False
    rel = _rel(file_path)
    # Never re-trigger on the appendix file itself (would loop).
    if rel == _rel(APPENDIX_PATH):
        return False
    if rel == "manuscript_02.qmd":
        return True
    if rel.startswith(("model/", "agents/")) and rel.endswith(".py"):
        return True
    if rel in WATCHED_SCRIPTS:
        return True
    return False


_CHUNK_OPEN = re.compile(r"^```\{(python|r)\b[^}]*\}\s*$", re.IGNORECASE)
_LABEL = re.compile(r"^#\|\s*label:\s*(fig-[\w.-]+)")
_SCAP  = re.compile(r"^#\|\s*fig-scap:\s*(.+)$")


def _strip_quotes(s: str) -> str:
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ("'", '"'):
        s = s[1:-1]
    return s.strip()


def extract_viz_chunks(qmd_text: str) -> list[tuple[str, str, str, str]]:
    """Return [(label, title, lang, code)] for chunks whose label starts with `fig-`.

    `title` comes from the `#| fig-scap: "..."` line if present (clean reader-
    friendly title), falling back to the figure label otherwise.
    """
    out: list[tuple[str, str, str, str]] = []
    lines = qmd_text.split("\n")
    i = 0
    while i < len(lines):
        m = _CHUNK_OPEN.match(lines[i])
        if not m:
            i += 1
            continue
        lang = m.group(1).lower()
        start = i + 1
        j = start
        while j < len(lines) and not lines[j].startswith("```"):
            j += 1
        body = lines[start:j]
        label = None
        scap = None
        for ln in body:
            if label is None:
                lm = _LABEL.match(ln)
                if lm:
                    label = lm.group(1)
            if scap is None:
                sm = _SCAP.match(ln)
                if sm:
                    scap = _strip_quotes(sm.group(1))
            if label and scap:
                break
        if label:
            title = scap or label
            out.append((label, title, lang, "\n".join(body).rstrip()))
        i = j + 1
    return out


def _tex_safe(s: str) -> str:
    """Escape underscores for use inside LaTeX section/subsection arguments."""
    return s.replace("_", r"\_")


HEADER = r"""\phantomsection
\section*{Appendix B: Visualization \& Simulation Code}
\addcontentsline{toc}{section}{Appendix B: Visualization \& Simulation Code}

This appendix is auto-generated from current source by
\texttt{scripts/regen\_viz\_appendix.py}, triggered by a \texttt{PostToolUse}
hook in \texttt{.claude/settings.json} whenever a watched file is edited.
Do not edit this file directly -- changes are overwritten on the next sync.
To change what is included, edit \texttt{WATCHED\_SCRIPTS} (or \texttt{MODEL\_DIR})
in the regenerator. The PDF is not auto-rebuilt; run
\texttt{quarto render manuscript\_02.qmd} when ready to publish.
"""


# Maximum source-file lines emitted per fenced code block.  Beyond this the
# pandoc-default Shaded environment (and even mdframed) overflows the LaTeX
# `\dimen@` register that holds the box height — `\fb@put@frame` errors with
# "Dimension too large".  Splitting the listing into ~300-line chunks with a
# tiny continuation header keeps every block within a renderable height.
MAX_BLOCK_LINES = 300


def _emit_python_listing(parts: list[str], rel: str, code: str) -> None:
    """Append a python listing to `parts`, splitting long files into chunks."""
    src_lines = code.split("\n")
    if len(src_lines) <= MAX_BLOCK_LINES:
        parts.append("```{.python}")
        parts.append(code)
        parts.append("```")
        parts.append("")
        return

    # Long file: break at MAX_BLOCK_LINES boundaries with continuation banners.
    n_chunks = (len(src_lines) + MAX_BLOCK_LINES - 1) // MAX_BLOCK_LINES
    for i in range(n_chunks):
        lo = i * MAX_BLOCK_LINES
        hi = min(len(src_lines), lo + MAX_BLOCK_LINES)
        chunk = "\n".join(src_lines[lo:hi])
        if i > 0:
            parts.append(
                rf"\par\noindent{{\small\itshape{{}}\dotfill\ {_tex_safe(rel)} "
                rf"(lines {lo+1}--{hi} of {len(src_lines)})\ \dotfill}}"
            )
            parts.append("")
        parts.append("```{.python}")
        parts.append(chunk)
        parts.append("```")
        parts.append("")


def render() -> str:
    parts: list[str] = [HEADER, ""]

    # ── B.1  Visualization code blocks (extracted from the manuscript) ─────────
    parts.append(r"\subsection*{B.1 \quad Visualization Code Blocks (from \texttt{manuscript\_02.qmd})}")
    parts.append("")
    if QMD_PATH.exists():
        chunks = extract_viz_chunks(QMD_PATH.read_text(encoding="utf-8"))
    else:
        chunks = []
    if not chunks:
        parts.append("_No `fig-*` chunks found._")
        parts.append("")
    else:
        for label, title, lang, code in chunks:
            # Heading: clean reader-friendly title with the chunk label as a
            # subdued reference (so a reader cross-checking against the body
            # of the manuscript can still find the source chunk).
            parts.append(
                rf"\subsubsection*{{{_tex_safe(title)} "
                rf"\hfill {{\small\texttt{{{_tex_safe(label)}}}}}}}"
            )
            parts.append("")
            parts.append("```{." + lang + "}")
            parts.append(code)
            parts.append("```")
            parts.append("")

    # ── B.2  Agent + Model source ──────────────────────────────────────────────
    parts.append(r"\subsection*{B.2 \quad Agent \& Model Source (\texttt{agents/}, \texttt{model/})}")
    parts.append("")
    src_files: list[Path] = []
    for d in (AGENTS_DIR, MODEL_DIR):
        if d.is_dir():
            src_files.extend(
                sorted(p for p in d.glob("*.py") if p.name != "__init__.py")
            )
    for path in src_files:
        rel = _rel(path)
        # Heading: bare filename for readability, full relative path as small ref.
        parts.append(
            rf"\subsubsection*{{{_tex_safe(path.name)} "
            rf"\hfill {{\small\texttt{{{_tex_safe(rel)}}}}}}}"
        )
        parts.append("")
        _emit_python_listing(parts, rel, path.read_text(encoding="utf-8").rstrip())

    # ── B.3  Preprocessing & configuration scripts ─────────────────────────────
    parts.append(r"\subsection*{B.3 \quad Preprocessing \& Configuration Scripts}")
    parts.append("")
    for rel in WATCHED_SCRIPTS:
        path = ROOT / rel
        if not path.exists():
            continue
        parts.append(
            rf"\subsubsection*{{{_tex_safe(path.name)} "
            rf"\hfill {{\small\texttt{{{_tex_safe(rel)}}}}}}}"
        )
        parts.append("")
        _emit_python_listing(parts, rel, path.read_text(encoding="utf-8").rstrip())

    return "\n".join(parts).rstrip() + "\n"


def main(argv: list[str]) -> int:
    triggered_by = "manual"

    if "--hook" in argv:
        # Read tool-call JSON from stdin; bail silently if it isn't ours.
        try:
            payload = json.load(sys.stdin)
        except Exception:
            return 0
        tool_input = (payload or {}).get("tool_input") or {}
        file_path = (
            tool_input.get("file_path")
            or tool_input.get("notebook_path")
            or ""
        )
        if not hook_should_run(file_path):
            return 0
        triggered_by = f"hook ({Path(file_path).name})"

    new = render()
    APPENDIX_PATH.parent.mkdir(parents=True, exist_ok=True)
    old = APPENDIX_PATH.read_text(encoding="utf-8") if APPENDIX_PATH.exists() else ""
    if new != old:
        APPENDIX_PATH.write_text(new, encoding="utf-8")
        print(
            f"[regen_viz_appendix] updated {_rel(APPENDIX_PATH)} ({triggered_by})",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
